title: Complication Watch Faces
author: Csaba Toth
email: csaba.toth.us@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  About Complication Watch Faces

twitter_username: tocsa2
github_username:  MrCsabaToth

# google_analytics: UA-86563829-5

vfd:
  app_url: https://play.google.com/store/apps/details?id=dev.csaba.vfdwatchface
  src_url: https://github.com/CsabaConsulting/VFDWatchFace

flower:
  app_url: https://play.google.com/store/apps/details?id=dev.csaba.complicationflowerwatchface
  src_url: https://github.com/CsabaConsulting/FlowerComplicationWatchFace

exclude:
  - "LICENSE"
  - "README.md"
  - ".gitignore"
plugins:
  - jekyll-redirect-from

sass:
    style: compressed
theme: jekyll-theme-minimal
